### ISSUE TITLE
Panic on Go 1.8 struct conversion ignoring field tags.

### ISSUE THREAD

**Issue by shurcooL** [mvdan/unparam#10]
```
$ go get -u github.com/mvdan/unparam
$ go get -u github.com/shurcooL/users/fs
$ unparam github.com/shurcooL/users/fs
panic: in github.com/shurcooL/users/fs.fromUserSpec: cannot convert *t0 (github.com/shurcooL/users.UserSpec) to github.com/shurcooL/users/fs.userSpec

goroutine 775 [running]:
golang.org/x/tools/go/ssa.emitConv(0xc4274f5400, 0x13fe440, 0xc42f56dda0, 0x13fa400, 0xc42711d2f0, 0xc42f56dda0, 0xc42f4fee40)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/golang.org/x/tools/go/ssa/emit.go:242 +0x9e5
golang.org/x/tools/go/ssa.(*builder).expr0(0xc42e085d00, 0xc4274f5400, 0x13fae40, 0xc420013dc0, 0x7, 0x13fa400, 0xc42711d2f0, 0x0, 0x0, 0xc420030800, ...)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/golang.org/x/tools/go/ssa/builder.go:573 +0x30f0
golang.org/x/tools/go/ssa.(*builder).expr(0xc42e085d00, 0xc4274f5400, 0x13fae40, 0xc420013dc0, 0x104b0c0, 0xc420030800)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/golang.org/x/tools/go/ssa/builder.go:530 +0x299
golang.org/x/tools/go/ssa.(*builder).stmt(0xc42e085d00, 0xc4274f5400, 0x13fb500, 0xc4200fea60)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/golang.org/x/tools/go/ssa/builder.go:2045 +0x1f6c
golang.org/x/tools/go/ssa.(*builder).stmtList(0xc42e085d00, 0xc4274f5400, 0xc420011650, 0x1, 0x1)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/golang.org/x/tools/go/ssa/builder.go:790 +0x61
golang.org/x/tools/go/ssa.(*builder).stmt(0xc42e085d00, 0xc4274f5400, 0x13fadc0, 0xc4200e6cf0)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/golang.org/x/tools/go/ssa/builder.go:2102 +0x2df7
golang.org/x/tools/go/ssa.(*builder).buildFunction(0xc42e085d00, 0xc4274f5400)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/golang.org/x/tools/go/ssa/builder.go:2195 +0x35c
golang.org/x/tools/go/ssa.(*builder).buildFuncDecl(0xc42e085d00, 0xc426f49620, 0xc4200e6d20)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/golang.org/x/tools/go/ssa/builder.go:2225 +0x12e
golang.org/x/tools/go/ssa.(*Package).build(0xc426f49620)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/golang.org/x/tools/go/ssa/builder.go:2341 +0x684
golang.org/x/tools/go/ssa.(*Package).(golang.org/x/tools/go/ssa.build)-fm()
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/golang.org/x/tools/go/ssa/builder.go:2260 +0x2a
sync.(*Once).Do(0xc426f4964c, 0xc42c49af98)
	/usr/local/go/src/sync/once.go:44 +0xbe
golang.org/x/tools/go/ssa.(*Package).Build(0xc426f49620)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/golang.org/x/tools/go/ssa/builder.go:2260 +0x55
golang.org/x/tools/go/ssa.(*Program).Build.func1(0xc42c3ac8e0, 0xc426f49620)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/golang.org/x/tools/go/ssa/builder.go:2244 +0x2b
created by golang.org/x/tools/go/ssa.(*Program).Build
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/golang.org/x/tools/go/ssa/builder.go:2246 +0x141
```

Problem line:

https://github.com/shurcooL/users/blob/16fca626b3e90416822651350babb0667b2bbe33/fs/schema.go#L79

It's the new-to-Go-1.8 struct conversion that ignores struct field tags.

**Comment by mvdan** [comment]
I've got good and bad news. The good is that I can reproduce. The bad is that it's a go/ssa bug. The good is that it's already reported and a CL was sent. The bad is that it's being ignored :)

https://github.com/golang/go/issues/19646
