### ISSUE TITLE
panic: interface conversion: ast.Expr is *ast.IndexExpr, not *ast.Ident

### ISSUE THREAD

**Issue by ainar-g** [mvdan/unparam#62]
The generics support in `golang.org/x/tools/go/ssa` seems to be mostly ready (see <https://github.com/golang/go/issues/48525#issuecomment-1128385150>), so I've updated it to the latest `master` commit, compiled `unparam`, and tried using it on some generic code.  The result is a panic:

```none
panic: interface conversion: ast.Expr is *ast.IndexExpr, not *ast.Ident

goroutine 1 [running]:
mvdan.cc/unparam/check.recvPrefix(...)
        /home/ainar/go/pkg/mod/mvdan.cc/unparam@v0.0.0-20220316160445-06cc5682983b/check/check .go:880
mvdan.cc/unparam/check.(*Checker).declCounts(0xc000124960, {0xc0001c0c80, 0x2a}, {0xc0001c9fe8 , 0x6})
        /home/ainar/go/pkg/mod/mvdan.cc/unparam@v0.0.0-20220316160445-06cc5682983b/check/check .go:855 +0x3f4
mvdan.cc/unparam/check.(*Checker).multipleImpls(0xc000124960, 0xc0001dbe00, 0xc002cc2000)
        /home/ainar/go/pkg/mod/mvdan.cc/unparam@v0.0.0-20220316160445-06cc5682983b/check/check.go:893 +0x105
mvdan.cc/unparam/check.(*Checker).checkFunc(0xc000124960, 0xc002cc2000, 0xc0001c0c80?)
        /home/ainar/go/pkg/mod/mvdan.cc/unparam@v0.0.0-20220316160445-06cc5682983b/check/check.go:493 +0x27e
mvdan.cc/unparam/check.(*Checker).Check(0xc000124960)
        /home/ainar/go/pkg/mod/mvdan.cc/unparam@v0.0.0-20220316160445-06cc5682983b/check/check.go:377 +0x76b
mvdan.cc/unparam/check.(*Checker).lines(0xc000124960, {0xc000010190?, 0x4c736f?, 0x40c8c5?})
        /home/ainar/go/pkg/mod/mvdan.cc/unparam@v0.0.0-20220316160445-06cc5682983b/check/check.go:107 +0x16a
mvdan.cc/unparam/check.UnusedParams(0x0, 0x0, 0x0, {0xc000010190, 0x2, 0x2})
        /home/ainar/go/pkg/mod/mvdan.cc/unparam@v0.0.0-20220316160445-06cc5682983b/check/check.go:44 +0xe5
main.main1()
        /home/ainar/go/pkg/mod/mvdan.cc/unparam@v0.0.0-20220316160445-06cc5682983b/main.go:37 +0x151
main.main()
        /home/ainar/go/pkg/mod/mvdan.cc/unparam@v0.0.0-20220316160445-06cc5682983b/main.go:23 +0x19
```

The reproducer code:

```go
package main

type set[T comparable] struct {
	m map[T]struct{}
}

func (s set[T]) has(v T) (ok bool) {
	_, ok = s.m[v]

	return ok
}

func main() {
	s := set[int]{}
	_ = s.has(0)
}
```

Versions:

```sh
go version -m ./bin/unparam
```

```none
./bin/unparam: go1.18.2
        path    mvdan.cc/unparam
        mod     mvdan.cc/unparam        v0.0.0-20220316160445-06cc5682983b      h1:C8Pi6noat8BcrL9WnSRYeQ63fpkJk3hKVHtF5731kIw=
        dep     golang.org/x/mod        v0.6.0-dev.0.20220419223038-86c51ed26bb4        h1:6zppjxzCulZykYSLyVDYbneBfbaBIQPYMevg0bEwv2s=
        dep     golang.org/x/sys        v0.0.0-20220513210249-45d2b4557a2a      h1:N2T1jUrTQE9Re6TFF5PhvEHXHCguynGhKjWVsIUt5cY=
        dep     golang.org/x/tools      v0.1.11-0.20220517032152-814e0d74b53f   h1:uWV+yNYrw4eleKDoYWdMeHM4sAErndcO+Z71LxvDNvA=
        build   -compiler=gc
        build   CGO_ENABLED=1
        build   CGO_CFLAGS=
        build   CGO_CPPFLAGS=
        build   CGO_CXXFLAGS=
        build   CGO_LDFLAGS=
        build   GOARCH=amd64
        build   GOOS=linux
        build   GOAMD64=v1
```

**Comment by mvdan** [comment]
I haven't looked at supporting generics in unparam yet; my thinking was waiting until go/ssa fully supports them.

**Comment by ainar-g** [comment]
Pardon for not reviewing in time.  I don't have the original code that triggered the issue by me right now, but running it on other generic code doesn't panic.
